spring:
  cloud:
    stream:
      function:
        definition: testConsumerPrak
      bindings:
        input:
          destination: testTopic
      kafka:
        binder:
          brokers: localhost:9092
